app:
  test: apptest
  scheduler:
    interval: 10000
    check-interval: 10000
  database-access-type: jdbc
  use-queue: true
  queue-name: "queue"
  exchange-name: "exchange"

server:
  port: 8081

springdoc:
  swagger-ui:
    path: "/swagger-ui"

github:
  base-url: https://api.github.com/repos/
  url: https://api.github.com/repos/

stackoverflow:
  base-url: https://api.stackexchange.com/2.3/questions/
  url: https://api.stackexchange.com/2.3/questions/

bot:
  base-url: http://localhost:8082
  url: http://localhost:8082

spring:
  liquibase:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    username: user
    password: 1234

management:
  server:
    port: 8090
  endpoints:
    enabled-by-default: false
    web:
      base-path: /
      exposure:
        include: ["info", "health", "prometheus"]
      path-mapping:
        prometheus: metrics
  endpoint:
    info.enabled: true
    health:
      enabled: true
      probes.enabled: true
      group:
        readiness.include: db
        liveness.include: ping
    prometheus.enabled: true
  metrics.tags:
    application: ${spring.application.name}
