app:
  test: apptest
  token: ${TOKEN}
  queue-name: "queue"
  exchange-name: "exchange"
  routingkey-name: ""
  use-queue: true

server:
  port: 8082

scrapper:
  base-url: http://localhost:8081
  url: http://localhost:8081

springdoc:
  swagger-ui:
    path: "/swagger-ui"

spring:
  rabbitmq:
    listener:
      simple:
        default-requeue-rejected: false