on:
  push:
    paths:
      - 'scrapper/**'
      - '.github/workflows/scrapper.yml'
      - 'link-parser/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn package -pl bot -am
      - name: Build image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/scrapper:latest ./scrapper
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/scrapper:latest